train:
    epoch: 1000
    batch_size: 4
    valid_size: 1
    num_workers: 0
    save_model: False
    load_model: False
    device: 'cuda:0'
    record_loss: False
    interval:
        save_model: 1000
        save_examples: 1000
        log: 100
    dir:
        save_examples: "examples"
        log: 'log.txt'

dataset:
    image_size: 512
    hint:
        radius_range: [2, 16]
        proportion_range: [0, 0.0005]
    dir:
        root: "dataset"
        train: "train"
        val: "val"

model:
    gen:
        in_ch: 7
        depth: [1, 1, 1, 1, 9, 9, 6, 6, 3]
        dims: [64, 128, 256, 512, 1024]
        attn: 1
        drop_path_rate: 0.2
        scale: 2
        layer_scale_init_value: 0.00001
        lr: 0.0002
        b1: 0.5
        b2: 0.99
    disc:
        in_ch: 6
        depth: [2, 2, 6, 2]
        dims: [96, 192, 384, 768]
        drop_path_rate: 0.2
        scale: 4
        layer_scale_init_value: 0.00001
        num_D: 3
        patch: True
        lr: 0.0002
        b1: 0.5
        b2: 0.99
    dir:
        root: "weights"
        gen: "gen"
        disc: "disc"
        ext: ".pt"

loss:
    adv: 0.1
    fm: 1.0
    vgg: 1000000.0
    l1: 1.0
    tv: 0
    gp: 0
