train:
    epoch: 200
    batch_size: 1
    valid_size: 1
    num_workers: 1
    save_model: True
    load_model: True
    logger: True
    device: 'cuda'
    interval:
        save_model: 1
        save_examples: 1
        logiter: 20
    dir:
        log: "./logs"
        save_examples: "./examples"

dataset:
    train_size: 512
    valid_size: 512
    # dir -> ./images/train/color/
    dir:
        root: "./images"
        train: "train"
        val: "val"
        color: "color"
        sketch: "sketch"

model:
    gen:
        base: 64
        in_ch: 5
        lr: 0.0002
        b1: 0.5
        b2: 0.999
        num_layers: 10
        up_layers: [10, 5, 5, 3]
    disc:
        base: 64
        in_ch: 4
        multi: 3
        lr: 0.0002
        b1: 0.5
        b2: 0.999
        num_layers: 4
    dir:
        gen: "./weights/gen.pth.tar"
        disc: "./weights/disc.pth.tar"

loss:
    advtype: "w"
    l1: 100
    adv: 0.0001
    fm: 1
    vgg: 10000
    gp: 1
